# app/constants.py

TASK_STATUS_PENDING = "PENDING_APPROVAL"
TASK_STATUS_APPROVED = "APPROVED"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_ERROR = "ERROR"

IMAGE_EXTENSIONS = ["png", "jpg", "jpeg"]